//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBlueSoft_parte3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuentas()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> TipoId { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public string CiudadOrigen { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
