//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaBlueSoft_parte3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int Id { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string TipoTransaccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
